//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityGroup
    {
        public ActivityGroup()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int ActivityGroupID { get; set; }
        public string ActivityGroupCode { get; set; }
        public string ActivityGroupName { get; set; }
        public Nullable<int> ActivityGroupType { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
