//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public int ActivityGroupID { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
    
        public virtual ActivityGroup ActivityGroup { get; set; }
    }
}
