//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualDetail
    {
        public int ActualDetailID { get; set; }
        public int ActualID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ActivityGroupID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> NumActivities { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Actual Actual { get; set; }
    }
}
