//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetDetail
    {
        public int BudgetDetailID { get; set; }
        public int BudgetID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ActivityGroupID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Percent { get; set; }
    
        public virtual Budget Budget { get; set; }
    }
}
