//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servier.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int SectorID { get; set; }
        public string SectorName { get; set; }
        public int RegionID { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual Region Region { get; set; }
    }
}
